#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
#
# Обновление сервера, когда docker.io не отдаёт слои базового образа.
# Код запечён в образ (Dockerfile: COPY app ./app), поэтому `git pull` без
# пересборки ничего не меняет, а пересборка упирается в реестр. Сценарий
# проводит через зеркало, сборку, миграцию и старт — по одному шагу за раз.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

BASE_IMAGE="python:3.11-slim"
DAEMON_JSON="/etc/docker/daemon.json"
MIRRORS_DEFAULT="https://mirror.gcr.io"
IPV6_DISABLED=""

banner "Обновление семейного ассистента"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Проверка: где мы и что запущено"
say "Браузер здесь не нужен — всё происходит в этой консоли."
say ""

if [[ ! -f docker-compose.yml ]]; then
  warn "Рядом нет docker-compose.yml."
  say "Запускайте из корня проекта: cd ~/FamilyAssistant/FamilyAssistant && bash scripts/upgrade.sh"
  exit 1
fi
note "каталог проекта: $(pwd)"

for tool in docker git curl; do
  command -v "$tool" >/dev/null 2>&1 || { warn "не найден $tool"; exit 1; }
done
docker compose version >/dev/null 2>&1 || { warn "нет плагина docker compose (v2)"; exit 1; }
note "docker и docker compose на месте"

HEAD_SHA=$(git rev-parse --short HEAD 2>/dev/null || echo "?")
note "коммит рабочей копии: $HEAD_SHA"
if ! git merge-base --is-ancestor 4e3c196 HEAD 2>/dev/null; then
  warn "В рабочей копии нет редизайна — сначала git pull."
  # Отказ здесь не ошибка: человек мог пуллить в другой копии. Поэтому
  # ветка «нет» гасится явно, иначе set -e молча уронил бы сценарий.
  if confirm "Сделать git pull прямо сейчас?"; then
    git pull --ff-only || warn "git pull не прошёл — разберитесь с ним отдельно"
  else
    note "пропускаю — но собирать будем то, что лежит сейчас"
  fi
fi

# Порт панели: из .env, иначе умолчание compose.
WEB_PORT=$(grep -E '^WEB_PORT=' .env 2>/dev/null | tail -n1 | cut -d= -f2- || true)
WEB_PORT="${WEB_PORT:-5000}"
note "панель ожидается на порту $WEB_PORT"
pause "Дальше — проверим, как сервер ходит в Docker Hub."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Диагностика: почему не качается образ"
say "Слои базового образа шли по IPv6 и отваливались по таймауту."
say "Проверим оба маршрута до реестра, по 8 секунд на попытку."
say ""

# curl печатает код и при обрыве («000»), поэтому «не дозвонились» ловим
# отдельно — иначе диагноз построился бы на строке вида «000таймаут».
probe() {
  local code
  code=$(curl "$1" -sS -m 8 -o /dev/null -w '%{http_code}' https://registry-1.docker.io/v2/ 2>/dev/null) || code=""
  # 401 — нормальный ответ реестра без токена: связь есть.
  if [[ -z "$code" || "$code" == "000" ]]; then printf 'таймаут'; else printf '%s' "$code"; fi
}
v4=$(probe -4)
v6=$(probe -6)
note "по IPv4: $v4"
note "по IPv6: $v6"
say ""
if [[ "$v4" != "таймаут" && "$v6" == "таймаут" ]]; then
  say "Диагноз: IPv4 работает, IPv6 глухой. Зеркало, скорее всего, поможет;"
  say "если нет — на шаге 4 будет возможность временно погасить IPv6."
elif [[ "$v4" == "таймаут" && "$v6" == "таймаут" ]]; then
  say "Диагноз: Docker Hub недоступен по обоим маршрутам. Нужно зеркало."
else
  say "Реестр отвечает — возможно, отваливается только CDN со слоями."
  say "Зеркало обходит и это: слои поедут с другого хоста."
fi
pause "Настроим зеркало?"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Зеркало Docker Hub"
say "Зеркало — это кеш Docker Hub на другом хосте. Образы те же самые,"
say "меняется только то, откуда они едут."
say ""
step "1) https://mirror.gcr.io — кеш Hub от Google, без регистрации"
step "2) https://cr.yandex/mirror — зеркало Яндекса"
step "3) оба, по очереди"
say ""
note "Сторонние зеркала не предлагаю: через них поедет код, который вы"
note "запускаете дома, и доверять их содержимому не на чем."
say ""
printf '  %sНомер (Enter — 1):%s ' "$BOLD" "$RESET"
read -r mirror_choice || true
case "${mirror_choice:-1}" in
  2) MIRRORS='"https://cr.yandex/mirror"' ;;
  3) MIRRORS='"https://mirror.gcr.io", "https://cr.yandex/mirror"' ;;
  *) MIRRORS="\"$MIRRORS_DEFAULT\"" ;;
esac
say ""
say "Правим $DAEMON_JSON — потребуется sudo."
say "Старый файл сохраню рядом с меткой времени, ничего не потеряется."
confirm "Продолжаем?" || { warn "Отменено."; exit 1; }

if [[ -f "$DAEMON_JSON" ]]; then
  BACKUP="${DAEMON_JSON}.bak.$(date +%Y%m%d-%H%M%S)"
  sudo cp "$DAEMON_JSON" "$BACKUP"
  note "копия старого файла: $BACKUP"
fi

# Дописываем ключ, а не перезаписываем файл: там могут лежать чужие настройки.
if command -v python3 >/dev/null 2>&1; then
  printf '[%s]' "$MIRRORS" | sudo python3 -c '
import json, sys, pathlib
mirrors = json.load(sys.stdin)
path = pathlib.Path("/etc/docker/daemon.json")
config = {}
if path.exists() and path.read_text().strip():
    try:
        config = json.loads(path.read_text())
    except ValueError:
        print("  старый daemon.json не разбирается как JSON — перезаписываю целиком")
config["registry-mirrors"] = mirrors
path.write_text(json.dumps(config, indent=2, ensure_ascii=False) + "\n")
print("  registry-mirrors =", ", ".join(mirrors))
'
else
  printf '{\n  "registry-mirrors": [%s]\n}\n' "$MIRRORS" | sudo tee "$DAEMON_JSON" >/dev/null
  note "python3 не найден — файл записан целиком"
fi

say ""
say "Перезапускаю docker. Контейнеры с restart:unless-stopped поднимутся сами."
sudo systemctl restart docker
for _ in $(seq 1 30); do
  docker info >/dev/null 2>&1 && break
  sleep 1
done
docker info >/dev/null 2>&1 || { warn "docker не поднялся — смотрите: sudo journalctl -u docker -n 50"; exit 1; }
note "docker перезапущен"
pause "Пробуем скачать базовый образ."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Базовый образ $BASE_IMAGE"
say "Это тот самый слой, на котором всё вставало. Тянем его отдельно,"
say "до сборки: так видно, помогло зеркало или нет."
say ""

while true; do
  if docker pull "$BASE_IMAGE"; then
    say ""
    note "образ на месте"
    break
  fi
  say ""
  warn "Не скачалось."
  say ""
  step "1) повторить — бывает, что со второго раза проходит"
  step "2) сменить зеркало (вернёт на шаг 3)"
  step "3) временно погасить IPv6 на хосте и повторить"
  step "4) выйти"
  say ""
  printf '  %sНомер:%s ' "$BOLD" "$RESET"
  read -r retry || true
  case "${retry:-4}" in
    1) continue ;;
    2) warn "Перезапустите сценарий и выберите на шаге 3 другое зеркало."; exit 1 ;;
    3)
      say ""
      say "Гашу IPv6 на хосте — это обратимо, откат покажу в конце."
      confirm "Точно?" || continue
      sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1 >/dev/null
      sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1 >/dev/null
      sudo systemctl restart docker
      sleep 3
      IPV6_DISABLED="yes"
      SKIPPED+=("вернуть IPv6: sudo sysctl -w net.ipv6.conf.all.disable_ipv6=0 net.ipv6.conf.default.disable_ipv6=0 && sudo systemctl restart docker")
      note "IPv6 выключен, docker перезапущен — пробую снова"
      ;;
    *) warn "Выхожу. Образ так и не скачался — сборка без него не пойдёт."; exit 1 ;;
  esac
done
pause "Собираем образ приложения."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Сборка образа"
say "Базовый слой уже локально, дальше сборка в сеть почти не ходит:"
say "останется pip install по requirements.txt."
say ""
if ! docker compose build; then
  say ""
  warn "Сборка не прошла. Смотрите последние строки вывода выше."
  exit 1
fi
say ""
note "образ собран"
pause "Дальше — миграция базы."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Миграция базы"
say "Миграция 0009 добавляет users.theme — колонку оформления."
say "Существующие участники получат «Тёплое» по умолчанию."
say ""
note "Прогоняем ДО старта: create_all() живую базу не трогает, и без"
note "колонки каждый экран отдаст 500."
say ""
if ! docker compose run --rm web alembic upgrade head; then
  say ""
  warn "Миграция не прошла — не поднимайте сервисы, пока не разберётесь."
  say "Чаще всего это недоступная база: docker compose ps, docker compose logs db"
  exit 1
fi
say ""
note "схема обновлена (команда идемпотентна — повторный прогон промолчит)"
pause "Поднимаем сервисы."

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Старт"
docker compose up -d
say ""
say "В строках выше должно стоять Recreated или Started."
warn "Если снова Running — образ не пересобрался, и шаг 5 прошёл вхолостую."
pause "Проверим, что поехало новое."

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Проверка"
say "Спрашиваем сам сервер, а не браузер: у браузера свой кеш."
say ""
sleep 3
CSS=$(curl -s -m 10 "http://localhost:${WEB_PORT}/static/style.css" | head -20 || true)
if grep -q "Оформлений два" <<<"$CSS"; then
  printf '  %s✓%s style.css — новый\n' "$GREEN" "$RESET"
elif [[ -z "$CSS" ]]; then
  warn "панель не ответила на порту $WEB_PORT — docker compose logs web"
else
  warn "style.css старый: работает прежний образ, вернитесь к шагу 5"
fi

CHAT=$(curl -s -m 10 -o /dev/null -w '%{http_code}' "http://localhost:${WEB_PORT}/chat" || echo "нет ответа")
note "GET /chat → $CHAT   (302 — это редирект на вход, всё в порядке)"
if [[ "$CHAT" == "500" ]]; then
  warn "500 на /chat — почти наверняка не прошла миграция, вернитесь к шагу 6"
fi

say ""
say "Осталось открыть панель в браузере:"
step "первая загрузка может прийти старой — service worker отдаёт её из кеша"
step "перезагрузите страницу второй раз, и приедет новое оформление"
step "панель, установленная на телефон, — закрыть и открыть заново"
say ""
step "разговор теперь на /chat, а не на / — центральная кнопка снизу"
step "оформление переключается в «Профиль и агент» → «Оформление»"

if [[ -n "$IPV6_DISABLED" ]]; then
  say ""
  warn "IPv6 на хосте остался выключенным — верните, когда закончите:"
  note "sudo sysctl -w net.ipv6.conf.all.disable_ipv6=0 net.ipv6.conf.default.disable_ipv6=0"
  note "sudo systemctl restart docker"
fi

finish
